export const TE100_ANNUAL_PRODUCTION = 'TE100 ANNUAL PRODUCTION';
export const ALL_ANIMALS_OVERVIEW_REPORT = 'ALL ANIMALS OVERVIEW REPORT';
export const ANNUAL_ACTIVE_LIVESTOCK_REPORT = 'ANNUAL ACTIVE LIVESTOCK REPORT';
export const ANNUAL_ACTIVE_LIVESTOCK_RAM_MATES_REPORT = 'ANNUAL ACTIVE LIVESTOCK RAM MATES REPORT';